name: "Node PR Versioning"
description: "Upate node project version using githubs pull request labels"
author: "noowah"

branding:
  icon: "git-pull-request"
  color: "green"

inputs:
  github-token:
    description: "The GitHub token for authentication"
    required: true
  labels-minor:
    description: "The label to update Minor version"
    required: true
  labels-major:
    description: "The label to update Major version"
    required: true
  labels-patch:
    description: "The label to update Patch version"
    required: true
  commit-message:
    description: "The commit message"
    required: false
    default: "chore: version update {{version}} -> {{new-version}}"
  skip-commit:
    description: "Skip commit the changes to the repository"
    required: false
    default: "false"
  path:
    description: "The path to the package.json file"
    required: false
  create-tag:
    description: "Create a tag using new version"
    required: false
    default: "false"
  tag-name:
    description: "Tag name"
    required: false
    default: "v{{version}}"
  pr-number:
    description: "The pull request number"
    required: false
  dry-run:
    description: "Dry run the action"
    required: false
    default: "false"

runs:
  using: "node20"
  main: "dist/index.js"
