name: "PR Versioning"
description: "Upate version using PR labels"
author: "noowah"

inputs:
  gh-token:
    description: "The GitHub token for authentication"
    required: true
  label-minor:
    description: "The label to update Minor version"
    required: true
  label-major:
    description: "The label to update Major version"
    required: true
  label-patch:
    description: "The label to update Patch version"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
