name: "PR Versioning"
description: "Upate version using PR labels"
author: "noowah"

inputs:
  github-token:
    description: "The GitHub token for authentication"
    required: true
  labels-minor:
    description: "The label to update Minor version"
    required: true
  labels-major:
    description: "The label to update Major version"
    required: true
  labels-patch:
    description: "The label to update Patch version"
    required: true
  skip-commit:
    description: "Skip commit the changes to the repository"
    required: false
  path:
    description: "The path to the package.json file"
    required: false
    default: "."
  create-tag:
    description: "Create a tag using new version"
    required: false
    default: "true"
  pr-number:
    description: "The pull request number"
    required: false
  dry-run:
    description: "Dry run the action"
    required: false
    default: "false"

runs:
  using: "node16"
  main: "dist/index.js"
