name: "Hello"

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: ./
        with:
          name: "Noowah"
          gh-token: ${{ secrets.GITHUB_TOKEN }}
