name: "Test"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  hello-world:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: ./
        with:
          label: "Noowah"
          gh-token: ${{ secrets.GITHUB_TOKEN }}
